### ISSUE TITLE
Want to Submit Your Story ? Here is a chance for you. 

### ISSUE THREAD

**Issue by dipakkr** [dipakkr/A-to-Z-Resources-for-Students#1140]
Do you have an Interesting Story to share? **We are here to listen to your story.** 

- You don't need to have a high paying job or from a premier institution. If you have done something you worth consider sharing, please write your story here in the comments. 

Or, you can also drop a mail at `raj.deeepak@gmail.com`

Remember your story can inspire thousands of students out there !!

Feel free to drop a comment here, if you have any doubt.

**Comment by OGHP** [comment]
I've just completed a Code Fellows 8 week coding boot camp, an in-person coding academy, covering Foundations of Software Development and Intermediate Software Development. It was an intense schedule of lectures, labs, pair-programming, daily reading assignments, white-boarding, career development, and networking. Generally, I was immersed from 8am to 9pm Monday through Friday with my weekends consumed by solo lab and reading assignments.

Since graduating, people have been asking me all sorts of questions about my experience: "Was it hard?", "What did you learn?", and "Could a new-to-tech person benefit at a boot camp?"

These are the same questions that I was asking before I started my first day. Naturally, there's a bit of uncertainty when you commit to a boot camp that comes with a fear of the unknown. Not to mention the worry that you won't be as ready or as knowledgeable as the other students that are attending. With that, there's even a bit of imposter syndrome.

Perhaps I can help with some of those questions and uncertainties, here's what I experienced this summer at my Code Fellows boot camp:

"Was coding boot camp hard?"
Yes, definitely yes! Coding boot camps are not for the easily swayed, deterred, offended or over-emotional people. You legitimately do not have time to let any of that creep into your brain space because it will be like a rock under a skateboard wheel - you will fall! You can't let "you" get into your own head.

I believe that those feelings should be acknowledged, but then they should be quickly placed on a shelf to be processed at a later date. You will be overwhelmed with the new technical vocabulary and concepts, you may sweat while you white-board and get critical feedback about your thought processes, you'll have difficult daily CodeWars.com challenges, you will pair-program with people you do not necessarily gel with, and you will ask yourself "am I actually cut out for this?".

Stick with it!

You can't let the doubt seep in! Doubt led to some of my classmates falling behind in their reading and lab assignments. Getting behind in a boot camp is nearly irreversible due to the amount of new information that's fed to you by the hour and the new assignments that are posted each night.

Take a deep breath (or two, or three) and realize "Yes! I'm definitely cut out for this..bring it on!". Once you can say that to yourself, you become a gazelle with laser focused intentions because you realize that you are more than capable and there are skilled people available to help you, you're not alone. Code Fellows has a team of TA's that have all completed the same boot camps that you are going through, in addition to the instructor staff. Not to mention, you are surrounded by other students that can help you work through what you're struggling with. It truly felt like we were all in the trenches together and people were reaching out their hands to help, every chance they got.

"What did you learn at a coding boot camp?"
It's a little information about a lot of topics and it comes in the form of a firehose throughout each lecture, every day. It's a lot..seriously. Code Fellows says "what you learn on day 1 won't click until day 4, what you learn on day 2 won't click until day 5, etc etc.." - it's called stacked learning.

Each boot camp was 20 days long. There are 15 days of lecture and then 5 days for your group project (no lecture during this time). 

In the 201 boot camp, Foundations for Software Development, I learned about: git commands, Github, HTML, CSS boxes/layout, how to code review, .gitignore files, Javascript tables, Javascript logic for tables, Javascript forms, Canvas, chart.js, event listeners, adding audio/video, UI/UX, constructors, Javascript DOM manipulation/traversing, Javascript events, jQuery, local storage, JSON library, Javascript objects, animations/transforms, debugging in the console and MVP (minimal viable product).

In the 301 boot camp, Intermediate Software Development, I learned about: Agile web development, responsive design, white-boarding, CSS positioning, jQuery Events, Regular Expression (regex), handlebars templating, methods: .forEach(), .split(), .join(), .slice(), .splice(), .map(), .indexOf(), .filter(), .reverse(), .reduce(), .sort(), object iteration, npm, WRRC (Web Request Response Cycle), CRUD, client/server relationship, client side rendering, server side rendering, Node.js, SQL, AJAX, express.js, Postgres, MVC (model, controller, view), IIFE's (Immediately Invoked Function Expression), Deployment with Heroku, EJS (Embedded JS templating) including partials, API's (application programming interface), superagent, and the importance of .env files.
In addition, the Code Fellows curriculum required that we attend tech meet-ups, attend the Code Fellows Friday "Partner Power Hours", create personal pitch videos, write our resumes, have mock interviews with our peers, create a spreadsheet of career paths that we would be interested in (including details about the company such as the year they were founded, the CEO's name, their mission statement, a link to their upcoming calendar of events, and a link to someone on LinkedIn that could connect you to someone influential at that company).

All of this, in 15 class days per boot camp (told you it's a lot!)

"Could a new-to-tech person benefit at a boot camp?"
Yes! Before you can start at Code Fellows, there is pre-work that you are required to complete, and it will help prepare you for what you're walking into. The pre-work is quite lengthy for the 201 boot camp and a bit lighter for the 301 boot camp. For 201, one of your prerequisites will be completing a 30 hour Khan Academy course.

While you can just do the pre-work and then start your journey, my recommendation would be to spend several months (prior to enrolling) doing coding tutorials to better prepare yourself. My recommendations would be:

SoloLearn - these tutorials move quickly but you can’t advance without getting the mini-tests correct. Once you’ve completed a course, you can go back through and redo just the questions for a refresher (and you even get a certificate tag for LinkedIn!).

W3Schools – I’d recommend going one by one down the left column to get vocabulary under your belt. You can do this for HTML, CSS, and JS. This should take you awhile - but it’s very helpful and a great future reference.

Codecademy - this is an interactive learning tool for HTML, CSS, JS and React (part 1 & 2).

One of my favorite tutorial instructors is Wes Bos (he's a Canadian with a really fun personality!). He offers a few free tutorials and a couple that are paid. These are a bit more advanced, if you are completely new to coding, but don't let that bother you. Go ahead and take a peek, especially at his free Javascript 30 in 30 challenge.

The Code Fellows 201 and 301 boot camps are designed to give you the foundations of coding and deliver them in the form of a tsunami. As you are being taught new topics you will not fully grasp what you are learning, or even that you are learning. It will start to marinate with you, I promise, especially if you work through coding tutorials before you head in. You'll find yourself saying "Oh, this is ringing a bell!".

"Anything else I should know?"
If you've got a burning desire to become a coding ninja and the available time (and money) to immerse yourself in a coding boot camp, definitely go for it! Most boot camps will offer a full-time daytime track or a part-time evening track. If you choose Code Fellows I'd also recommend that in addition to the 201 and 301 boot camp, you continue on to the 401 Advanced Software Development boot camp.

The 201 and 301 are excellent foundational skill training. They tell you that technically you can walk out of there saying you're a full stack developer after 301. However, if you'd like to up your chances of a killer job opportunity then definitely consider one of their 401 tracks. Code Fellows offers 401: JavaScript, Java, .net, or Python.

So, are you thinking about a coding boot camp? Do you have any questions that I didn't cover? Please shoot me a message, I'd love to help if I can. And if you're all set and ready to dive into a boot camp, I wish you the best! Set your mind right and you'll come out of there a superstar!

**Comment by pahesali** [comment]
I don't have a very interesting story. But it manages to enter one of the best universities in my state and country.

At first it was difficult because I had to move and had no conditions and it was complicated to have to leave my city and go to another, but over time I realized that I learned a lot, both in the educational area in the area of ​​computing and social. In the new city I moved to the university housing and in it and in the city itself I met many people who helped and deconstructed me, making my prejudices lessened and I understood subjects that I found complex and difficult.

So if you have a goal you are after it is difficult because in the end there is almost always a reward, mine was the new friendships and incredible knowledge.

**Comment by gagangaur** [comment]
Hey, it would be better if we make section/folder(Inspiration Stories) for stories and people can make PR's instead of commenting down the stories here it would be a great step for newcomers towards opensource contribution.

**Comment by OGHP** [comment]
@gagangaur Love that idea! I'd be willing to take on this task - @dipakkr Let me know

**Comment by dipakkr** [comment]
Sorry for the late reply guys. I was offline from sometime due to some health issues. 

@gagangaur good idea !!

@OGHP Sure, You can work on it. 

Also, please make a template page for the story which people can follow while writing their story. And, I think there should columns for social links that people can share if they are willing to. 

Let me know what you guys think.

**Comment by gagangaur** [comment]
Ya @dipakkr  nice idea of adding social links if someone has written such stories on some other platforms like "quora" or "medium" then instead of copying it from there the can simply mention their links so that the readers can get a good experience of reading instead of reading on Github.😂
and can you guys please share some open source projects (react) which are good or comfortable for beginners to work on if you know then please do share some of those. Thanks😊

**Comment by Khushaliketan** [comment]
Hey. Along with what @gangangaur suggested, I think it'll be nice to sort what kind of stories we want this page to show. These can be inspirational, self-help, philosophical, quest etc. and the repo would look much more organised. 
Also if anyone has any info about other documentation/basic competitive coding issues that beginners can take up then please to share some of them here, thanks a lot! :)

**Comment by dipakkr** [comment]
@Khushaliketan People look for resources and success roadmap of others to decide or choose their own. That's why my idea was to keep the story informational, self-help and inspirational as well. 

Here is repo for competitive coding, do check it out : https://github.com/jwasham/coding-interview-university

**Comment by bhargavgana** [comment]
@dipakkr can you make a list of resources / learning paths for learning Cloud technologies like AWS, Azure, Google Cloud .
